/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface HeximalOperationsError {
  error: "Not a heximal number" | "Uncorrect input datatype: str need";
  operation_type: "multiply" | "add";
  [k: string]: unknown;
}
