/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface HeximalOperationsRequest {
  heximal_1: string;
  heximal_2: string;
  operation_type: "multiply" | "add";
  [k: string]: unknown;
}
