/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface MatrixOperationsError {
  error: "Matrix dimension mismatch" | "Uncorrect datatype of elements: integers need";
  operation_type: "multiply" | "add";
  [k: string]: unknown;
}
